name: Build Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    strategy:
      matrix:
        runner: [ubuntu-latest]
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: depot/setup-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: depot/build-push-action@v1
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/peerdb-io/pgslot-notify-bot:latest
            ghcr.io/peerdb-io/pgslot-notify-bot:${{ github.sha }}
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
